<?php

namespace AppBundle\Repository;

/**
 * InitialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InitialRepository extends \Doctrine\ORM\EntityRepository
{
}
