<?php

namespace AppBundle\Repository;

/**
 * MonitoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonitoringRepository extends \Doctrine\ORM\EntityRepository
{
}
