<?php

namespace AppBundle\Repository;

/**
 * PackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllPacksFoodAndFoodBody()
    {
        return $this->createQueryBuilder('p')
            ->where('p.pack_type != :type')
            ->setParameter('type', 'themes')
            ->getQuery()
            ->getResult();
    }

    public function getAllPacksThemes()
    {
        return $this->createQueryBuilder('p')
            ->where('p.pack_type = :type')
            ->setParameter('type', 'themes')
            ->getQuery()
            ->getResult();
    }
}
