<?php

namespace AppBundle\Repository;

/**
 * ResultExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultExerciseRepository extends \Doctrine\ORM\EntityRepository
{
}
