<?php

namespace AppBundle\Repository;

/**
 * ResultExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultExerciseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllResultExercisesByUser($user)
    {
        return $this->createQueryBuilder('re')
                ->leftJoin('re.result', 'r')
                ->leftJoin('r.pack', 'p')
                ->leftJoin('p.initial', 'i')
                ->where('i.id = :id')
                ->setParameter('id', $user->getId())
                ->getQuery()
                ->getResult()
            ;
    }


}
