app:
    resource: "@AppBundle/Controller/"
    type:     annotation

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: pack_index
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"        
